In [1]:
import torch

In [2]:
x = torch.arange(12, dtype = torch.float32)

In [3]:
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [4]:
x.numel()

12

In [5]:
X = x.reshape(3, 4)

In [6]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [7]:
torch.arange(15, dtype = torch.float32).reshape(3,5)

tensor([[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.]])

In [8]:
torch.zeros(2,2,3,4)

tensor([[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]],


        [[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]])

In [9]:
torch.zeros(2,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [10]:
torch.randn(3, 6)

tensor([[-0.2575,  1.8075,  0.5126, -0.6547, -0.7092, -1.7733],
        [ 0.5991, -0.4840,  0.6355,  0.3680,  1.1586, -1.2565],
        [ 0.1628, -0.8732, -0.4369,  0.3161, -1.4079,  1.1978]])

In [11]:
X[-1]

tensor([ 8.,  9., 10., 11.])

In [12]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [13]:
X[1][1]

tensor(5.)

In [14]:
X[-1][1:]

tensor([ 9., 10., 11.])

In [15]:
X[1:3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [16]:
X[1][2] = 17

In [17]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])

In [18]:
X[1,2] = 21
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 21.,  7.],
        [ 8.,  9., 10., 11.]])

In [19]:
X[:2, :1]

tensor([[0.],
        [4.]])

In [20]:
X[:3, :1] = 11

In [21]:
X

tensor([[11.,  1.,  2.,  3.],
        [11.,  5., 21.,  7.],
        [11.,  9., 10., 11.]])

In [22]:
x = torch.tensor([1., 2, 4, 8])
y = torch.tensor([2,2,2,2])
x + y, x - y, x * y, x / y, y / x, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([2.0000, 1.0000, 0.5000, 0.2500]),
 tensor([ 1.,  4., 16., 64.]))

In [23]:
torch.cat((x, y))

tensor([1., 2., 4., 8., 2., 2., 2., 2.])

In [24]:
torch.cat((x, y), dim = 0)

tensor([1., 2., 4., 8., 2., 2., 2., 2.])

In [25]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [26]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [27]:
X.sum()

tensor(66.)

### Broadcasting

In [28]:
a = torch.arange(3).reshape(3, 1)
b = torch.arange(2).reshape(1,2)

In [29]:
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [30]:
a / b

tensor([[nan, 0.],
        [inf, 1.],
        [inf, 2.]])

### Saving Memory

In [31]:
Z = torch.zeros_like(Y)
print('id(Z): ', id(Z))
Z[:] = X + Y
print('id(Z): ', id(Z))

id(Z):  2796065151536
id(Z):  2796065151536


In [32]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [33]:
X > Y

tensor([[False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

## 2.2 Data Preprocessing

In [34]:
import os
os.makedirs(os.path.join('.', 'data'), exist_ok=True)
data_file = os.path.join('.', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('''NumRooms,RoofType,Price
NA,NA,127500
2,NA,106000
4,Slate,178100
NA,NA,140000''')

In [35]:
import pandas as pd

data = pd.read_csv(data_file)
data.head()

NumRooms RoofType   Price
0       NaN      NaN  127500
1       2.0      NaN  106000
2       4.0    Slate  178100
3       NaN      NaN  140000

In [36]:
inputs, targets = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = pd.get_dummies(inputs, dummy_na=True)

In [37]:
inputs.head()

NumRooms  RoofType_Slate  RoofType_nan
0       NaN           False          True
1       2.0           False          True
2       4.0            True         False
3       NaN           False          True

In [38]:
inputs = inputs.fillna(inputs.mean())
inputs.head()

NumRooms  RoofType_Slate  RoofType_nan
0       3.0           False          True
1       2.0           False          True
2       4.0            True         False
3       3.0           False          True

In [39]:
X = torch.tensor(inputs.to_numpy(dtype=float))
y = torch.tensor(targets.to_numpy(dtype=float))
X, y

(tensor([[3., 0., 1.],
         [2., 0., 1.],
         [4., 1., 0.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500., 106000., 178100., 140000.], dtype=torch.float64))

In [40]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone()  # Assign a copy of A to B by allocating new memory
A, A + B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

In [41]:
A * B

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [42]:
A, A.sum()

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor(15.))

In [43]:
A, A.sum(axis = 0)

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([3., 5., 7.]))

In [44]:
A, A.sum(axis = 1)

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([ 3., 12.]))

In [45]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A, sum_A.shape

(tensor([[ 3.],
         [12.]]),
 torch.Size([2, 1]))

In [46]:
sum_A, A.shape

(tensor([[ 3.],
         [12.]]),
 torch.Size([2, 3]))

In [47]:
A / sum_A

tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167]])

In [48]:
sum_aa = A.sum(axis=1)
sum_aa, sum_aa.shape

(tensor([ 3., 12.]), torch.Size([2]))

In [49]:
x = torch.arange(3, dtype=torch.float32)
y = torch.ones(3, dtype = torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2.]), tensor([1., 1., 1.]), tensor(3.))

In [50]:
torch.mv(A, x)

tensor([ 5., 14.])

In [51]:
A@x

tensor([ 5., 14.])

In [52]:
B = torch.ones(3, 4)

In [53]:
A

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [54]:
x

tensor([0., 1., 2.])

In [55]:
torch.mm(A, B), A, B

(tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]),
 tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

In [66]:
C = torch.ones(3, 4)

In [67]:
import numpy as np

In [57]:
torch.dot(B[:, 1], C[:, 1])

tensor(3.)

In [58]:
D = torch.ones(4, 3)
torch.mm(C, D), C, D

(tensor([[4., 4., 4.],
         [4., 4., 4.],
         [4., 4., 4.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]))

In [59]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [60]:
torch.abs(u).sum()

tensor(7.)

In [61]:
torch.ones(4,9)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [62]:
torch.norm(torch.ones(4,9))

tensor(6.)

### Derivatives

In [64]:
def f(x):
    return 3 * x ** 2 - 4 * x

In [69]:
for h in 10.0**np.arange(-1, -6, -1):
    print(f'h={h:.5f}, numerical limit={(f(1+h)-f(1))/h:.5f}')

h=0.10000, numerical limit=2.30000
h=0.01000, numerical limit=2.03000
h=0.00100, numerical limit=2.00300
h=0.00010, numerical limit=2.00030
h=0.00001, numerical limit=2.00003


In [70]:
%matplotlib inline
from matplotlib_inline import backend_inline

In [71]:
def use_svg_display(): #@save
    """Use the svg format to display a plot in Jupyter."""
    backend_inline.set_matplotlib_formats('svg')

In [73]:
def set_figsize(figsize=(3.5, 2.5)):  #@save
    """Set the figure size for matplotlib."""
    use_svg_display()
    torch.plt.rcParams['figure.figsize'] = figsize

In [74]:
#@save
def set_axes(axes, xlabel, ylabel, xlim, ylim, xscale, yscale, legend):
    """Set the axes for matplotlib."""
    axes.set_xlabel(xlabel), axes.set_ylabel(ylabel)
    axes.set_xscale(xscale), axes.set_yscale(yscale)
    axes.set_xlim(xlim),     axes.set_ylim(ylim)
    if legend:
        axes.legend(legend)
    axes.grid()

In [75]:
#@save
def plot(X, Y=None, xlabel=None, ylabel=None, legend=[], xlim=None,
         ylim=None, xscale='linear', yscale='linear',
         fmts=('-', 'm--', 'g-.', 'r:'), figsize=(3.5, 2.5), axes=None):
    """Plot data points."""

    def has_one_axis(X):  # True if X (tensor or list) has 1 axis
        return (hasattr(X, "ndim") and X.ndim == 1 or isinstance(X, list)
                and not hasattr(X[0], "__len__"))

    if has_one_axis(X): X = [X]
    if Y is None:
        X, Y = [[]] * len(X), X
    elif has_one_axis(Y):
        Y = [Y]
    if len(X) != len(Y):
        X = X * len(Y)

    set_figsize(figsize)
    if axes is None:
        axes = d2l.plt.gca()
    axes.cla()
    for x, y, fmt in zip(X, Y, fmts):
        axes.plot(x,y,fmt) if len(x) else axes.plot(y,fmt)
    set_axes(axes, xlabel, ylabel, xlim, ylim, xscale, yscale, legend)

In [76]:
x = np.arange(0, 3, 0.1)
plot(x, [f(x), 2 * x - 3], 'x', 'f(x)', legend=['f(x)', 'Tangent line (x=1)'])

Unexpected exception formatting exception. Falling back to standard exception


Traceback (most recent call last):
  File "c:\Users\Jitto\Documents\Code\AICoding\AiGenAiLearnJourney\ailearnenv\Lib\site-packages\IPython\core\interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jitto\AppData\Local\Temp\ipykernel_9116\2506450218.py", line 2, in <module>
    plot(x, [f(x), 2 * x - 3], 'x', 'f(x)', legend=['f(x)', 'Tangent line (x=1)'])
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jitto\AppData\Local\Temp\ipykernel_9116\2786110055.py", line 19, in plot
    set_figsize(figsize)
    ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\Jitto\AppData\Local\Temp\ipykernel_9116\1899842612.py", line 4, in set_figsize
    torch.plt.rcParams['figure.figsize'] = figsize
    ^^^^^^^^^
  File "c:\Users\Jitto\Documents\Code\AICoding\AiGenAiLearnJourney\ailearnenv\Lib\site-packages\torch\__init__.py", line 2757, in __getattr__
 

### Automatic Differentiation

In [96]:
x = torch.arange(4.0)

In [97]:
x

tensor([0., 1., 2., 3.])

In [98]:
x.requires_grad_(True)
x.grad

In [99]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [86]:
m= torch.arange(9).reshape(3, 3)
m

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [84]:
v = torch.tensor([1,2,3])

In [85]:
m@v

tensor([ 8, 26, 44])

In [102]:
y.backward()
# y.backward()
# y.backward()
x.grad

Unexpected exception formatting exception. Falling back to standard exception


Traceback (most recent call last):
  File "c:\Users\Jitto\Documents\Code\AICoding\AiGenAiLearnJourney\ailearnenv\Lib\site-packages\IPython\core\interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jitto\AppData\Local\Temp\ipykernel_9116\983763472.py", line 1, in <module>
    y.backward()
    ~~~~~~~~~~^^
  File "c:\Users\Jitto\Documents\Code\AICoding\AiGenAiLearnJourney\ailearnenv\Lib\site-packages\torch\_tensor.py", line 625, in backward
    torch.autograd.backward(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        self, gradient, retain_graph, create_graph, inputs=inputs
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "c:\Users\Jitto\Documents\Code\AICoding\AiGenAiLearnJourney\ailearnenv\Lib\site-packages\torch\autograd\__init__.py", line 354, in backward
    _engine_run_backward(
    ~~~~~~~~~~~~~~~~~~~~^
        tensors,
        ^^^^^^^^
    .

In [103]:
x

tensor([0., 1., 2., 3.], requires_grad=True)

In [104]:
x.grad == 4 * x

tensor([True, True, True, True])

In [106]:
x.grad_zero_()

Unexpected exception formatting exception. Falling back to standard exception


Traceback (most recent call last):
  File "c:\Users\Jitto\Documents\Code\AICoding\AiGenAiLearnJourney\ailearnenv\Lib\site-packages\IPython\core\interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jitto\AppData\Local\Temp\ipykernel_9116\1478818022.py", line 1, in <module>
    x.grad_zero_()
    ^^^^^^^^^^^^
AttributeError: 'Tensor' object has no attribute 'grad_zero_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Jitto\Documents\Code\AICoding\AiGenAiLearnJourney\ailearnenv\Lib\site-packages\IPython\core\interactiveshell.py", line 2144, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
        etype, value, tb, tb_offset=tb_offset
    )
  File "c:\Users\Jitto\Documents\Code\AICoding\AiGenAiLearnJourney\ailearnenv\Lib\site-packages\IPython\core\ultratb.py", line 1435, in structure

In [108]:
x.grad.zero_()

tensor([0., 0., 0., 0.])

In [109]:
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

## Linear Regression

In [110]:
%matplotlib inline
import math
import time
import numpy as np
import torch