In [10]:
inputs = [1,2,3,2.5]

weights = [
    [0.2,0.8,-0.5,1.0],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
]

biases = [2,3,0.5]


# weights = [0.2,0.8,-0.5,1.0]

# biases = 2



In [2]:
import numpy as np

In [14]:
output = np.dot(weights, inputs) + biases
output

array([4.8  , 1.21 , 2.385])

In [16]:
inputs = [
    [1,2,3,2.5],
    [2,5,-1.0,2.0],
    [-1.5, 2.7, 3.3, -0.8]
]

In [18]:
output = np.dot(inputs, np.array(weights).T) + biases
output

array([[ 4.8  ,  1.21 ,  2.385],
       [ 8.9  , -1.81 ,  0.2  ],
       [ 1.41 ,  1.051,  0.026]])

In [20]:
biases2 = [-1,2,0.5]
weights2 = [
    [0.1,-0.14,0.5],
    [-0.5,0.12,-0.33],
    [-0.44,0.73,-0.13]
]

In [21]:
layer1_outputs = np.dot(inputs, np.array(weights).T) + biases

layer2_outputs = np.dot(layer1_outputs, np.array(weights2).T) + biases2

layer2_outputs

array([[ 0.5031 , -1.04185, -1.03875],
       [ 0.2434 , -2.7332 , -4.7633 ],
       [-0.99314,  1.41254,  0.64345]])

In [22]:
np.random.seed(0)

X = [
    [1,2,3,2.5],
    [2,5,-1.0,2.0],
    [-1.5, 2.7, 3.3, -0.8]
]

class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.1 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases
# General idea of weights is to have them bw -1 to 1 - lets start with -0.01 to 0.01

layer1 = Layer_Dense(4, 5)
layer2 = Layer_Dense(5, 2)

layer1.forward(X)
print(layer1.output)

[[ 0.10758131  1.03983522  0.24462411  0.31821498  0.18851053]
 [-0.08349796  0.70846411  0.00293357  0.44701525  0.36360538]
 [-0.50763245  0.55688422  0.07987797 -0.34889573  0.04553042]]


In [23]:
layer2.forward(layer1.output)
print(layer2.output)

[[ 0.148296   -0.08397602]
 [ 0.14100315 -0.01340469]
 [ 0.20124979 -0.07290616]]


In [27]:
inputs = [0,2,-1,3.3,-2.7,1.1,2.2,-100]

outputs = []

for i in inputs:
    outputs.append(max(0, i))

outputs

[0, 2, 0, 3.3, 0, 1.1, 2.2, 0]

In [ ]:
class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)

SyntaxError: incomplete input (392365044.py, line 1)